
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TransactionProduct` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TransactionProduct
 * 
 */
export type TransactionProductModel = runtime.Types.Result.DefaultSelection<Prisma.$TransactionProductPayload>

export type AggregateTransactionProduct = {
  _count: TransactionProductCountAggregateOutputType | null
  _avg: TransactionProductAvgAggregateOutputType | null
  _sum: TransactionProductSumAggregateOutputType | null
  _min: TransactionProductMinAggregateOutputType | null
  _max: TransactionProductMaxAggregateOutputType | null
}

export type TransactionProductAvgAggregateOutputType = {
  quantity: number | null
  unitPrice: number | null
  totalAmount: number | null
}

export type TransactionProductSumAggregateOutputType = {
  quantity: number | null
  unitPrice: number | null
  totalAmount: number | null
}

export type TransactionProductMinAggregateOutputType = {
  id: string | null
  productId: string | null
  transactionId: string | null
  quantity: number | null
  unitPrice: number | null
  totalAmount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TransactionProductMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  transactionId: string | null
  quantity: number | null
  unitPrice: number | null
  totalAmount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TransactionProductCountAggregateOutputType = {
  id: number
  productId: number
  transactionId: number
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TransactionProductAvgAggregateInputType = {
  quantity?: true
  unitPrice?: true
  totalAmount?: true
}

export type TransactionProductSumAggregateInputType = {
  quantity?: true
  unitPrice?: true
  totalAmount?: true
}

export type TransactionProductMinAggregateInputType = {
  id?: true
  productId?: true
  transactionId?: true
  quantity?: true
  unitPrice?: true
  totalAmount?: true
  createdAt?: true
  updatedAt?: true
}

export type TransactionProductMaxAggregateInputType = {
  id?: true
  productId?: true
  transactionId?: true
  quantity?: true
  unitPrice?: true
  totalAmount?: true
  createdAt?: true
  updatedAt?: true
}

export type TransactionProductCountAggregateInputType = {
  id?: true
  productId?: true
  transactionId?: true
  quantity?: true
  unitPrice?: true
  totalAmount?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TransactionProductAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TransactionProduct to aggregate.
   */
  where?: Prisma.TransactionProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionProducts to fetch.
   */
  orderBy?: Prisma.TransactionProductOrderByWithRelationInput | Prisma.TransactionProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TransactionProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TransactionProducts
  **/
  _count?: true | TransactionProductCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TransactionProductAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TransactionProductSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TransactionProductMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TransactionProductMaxAggregateInputType
}

export type GetTransactionProductAggregateType<T extends TransactionProductAggregateArgs> = {
      [P in keyof T & keyof AggregateTransactionProduct]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTransactionProduct[P]>
    : Prisma.GetScalarType<T[P], AggregateTransactionProduct[P]>
}




export type TransactionProductGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransactionProductWhereInput
  orderBy?: Prisma.TransactionProductOrderByWithAggregationInput | Prisma.TransactionProductOrderByWithAggregationInput[]
  by: Prisma.TransactionProductScalarFieldEnum[] | Prisma.TransactionProductScalarFieldEnum
  having?: Prisma.TransactionProductScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TransactionProductCountAggregateInputType | true
  _avg?: TransactionProductAvgAggregateInputType
  _sum?: TransactionProductSumAggregateInputType
  _min?: TransactionProductMinAggregateInputType
  _max?: TransactionProductMaxAggregateInputType
}

export type TransactionProductGroupByOutputType = {
  id: string
  productId: string
  transactionId: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt: Date
  updatedAt: Date
  _count: TransactionProductCountAggregateOutputType | null
  _avg: TransactionProductAvgAggregateOutputType | null
  _sum: TransactionProductSumAggregateOutputType | null
  _min: TransactionProductMinAggregateOutputType | null
  _max: TransactionProductMaxAggregateOutputType | null
}

type GetTransactionProductGroupByPayload<T extends TransactionProductGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TransactionProductGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TransactionProductGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TransactionProductGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TransactionProductGroupByOutputType[P]>
      }
    >
  >



export type TransactionProductWhereInput = {
  AND?: Prisma.TransactionProductWhereInput | Prisma.TransactionProductWhereInput[]
  OR?: Prisma.TransactionProductWhereInput[]
  NOT?: Prisma.TransactionProductWhereInput | Prisma.TransactionProductWhereInput[]
  id?: Prisma.StringFilter<"TransactionProduct"> | string
  productId?: Prisma.StringFilter<"TransactionProduct"> | string
  transactionId?: Prisma.StringFilter<"TransactionProduct"> | string
  quantity?: Prisma.IntFilter<"TransactionProduct"> | number
  unitPrice?: Prisma.IntFilter<"TransactionProduct"> | number
  totalAmount?: Prisma.IntFilter<"TransactionProduct"> | number
  createdAt?: Prisma.DateTimeFilter<"TransactionProduct"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TransactionProduct"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  transaction?: Prisma.XOR<Prisma.TransactionScalarRelationFilter, Prisma.TransactionWhereInput>
}

export type TransactionProductOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  transaction?: Prisma.TransactionOrderByWithRelationInput
}

export type TransactionProductWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TransactionProductWhereInput | Prisma.TransactionProductWhereInput[]
  OR?: Prisma.TransactionProductWhereInput[]
  NOT?: Prisma.TransactionProductWhereInput | Prisma.TransactionProductWhereInput[]
  productId?: Prisma.StringFilter<"TransactionProduct"> | string
  transactionId?: Prisma.StringFilter<"TransactionProduct"> | string
  quantity?: Prisma.IntFilter<"TransactionProduct"> | number
  unitPrice?: Prisma.IntFilter<"TransactionProduct"> | number
  totalAmount?: Prisma.IntFilter<"TransactionProduct"> | number
  createdAt?: Prisma.DateTimeFilter<"TransactionProduct"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TransactionProduct"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  transaction?: Prisma.XOR<Prisma.TransactionScalarRelationFilter, Prisma.TransactionWhereInput>
}, "id">

export type TransactionProductOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TransactionProductCountOrderByAggregateInput
  _avg?: Prisma.TransactionProductAvgOrderByAggregateInput
  _max?: Prisma.TransactionProductMaxOrderByAggregateInput
  _min?: Prisma.TransactionProductMinOrderByAggregateInput
  _sum?: Prisma.TransactionProductSumOrderByAggregateInput
}

export type TransactionProductScalarWhereWithAggregatesInput = {
  AND?: Prisma.TransactionProductScalarWhereWithAggregatesInput | Prisma.TransactionProductScalarWhereWithAggregatesInput[]
  OR?: Prisma.TransactionProductScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TransactionProductScalarWhereWithAggregatesInput | Prisma.TransactionProductScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TransactionProduct"> | string
  productId?: Prisma.StringWithAggregatesFilter<"TransactionProduct"> | string
  transactionId?: Prisma.StringWithAggregatesFilter<"TransactionProduct"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"TransactionProduct"> | number
  unitPrice?: Prisma.IntWithAggregatesFilter<"TransactionProduct"> | number
  totalAmount?: Prisma.IntWithAggregatesFilter<"TransactionProduct"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TransactionProduct"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TransactionProduct"> | Date | string
}

export type TransactionProductCreateInput = {
  id?: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutTransactionProductInput
  transaction: Prisma.TransactionCreateNestedOneWithoutProductsInput
}

export type TransactionProductUncheckedCreateInput = {
  id?: string
  productId: string
  transactionId: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionProductUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutTransactionProductNestedInput
  transaction?: Prisma.TransactionUpdateOneRequiredWithoutProductsNestedInput
}

export type TransactionProductUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionProductCreateManyInput = {
  id?: string
  productId: string
  transactionId: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionProductUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionProductUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionProductListRelationFilter = {
  every?: Prisma.TransactionProductWhereInput
  some?: Prisma.TransactionProductWhereInput
  none?: Prisma.TransactionProductWhereInput
}

export type TransactionProductOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TransactionProductCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransactionProductAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type TransactionProductMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransactionProductMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransactionProductSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type TransactionProductCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.TransactionProductCreateWithoutProductInput, Prisma.TransactionProductUncheckedCreateWithoutProductInput> | Prisma.TransactionProductCreateWithoutProductInput[] | Prisma.TransactionProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.TransactionProductCreateOrConnectWithoutProductInput | Prisma.TransactionProductCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.TransactionProductCreateManyProductInputEnvelope
  connect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
}

export type TransactionProductUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.TransactionProductCreateWithoutProductInput, Prisma.TransactionProductUncheckedCreateWithoutProductInput> | Prisma.TransactionProductCreateWithoutProductInput[] | Prisma.TransactionProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.TransactionProductCreateOrConnectWithoutProductInput | Prisma.TransactionProductCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.TransactionProductCreateManyProductInputEnvelope
  connect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
}

export type TransactionProductUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionProductCreateWithoutProductInput, Prisma.TransactionProductUncheckedCreateWithoutProductInput> | Prisma.TransactionProductCreateWithoutProductInput[] | Prisma.TransactionProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.TransactionProductCreateOrConnectWithoutProductInput | Prisma.TransactionProductCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.TransactionProductUpsertWithWhereUniqueWithoutProductInput | Prisma.TransactionProductUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.TransactionProductCreateManyProductInputEnvelope
  set?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  disconnect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  delete?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  connect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  update?: Prisma.TransactionProductUpdateWithWhereUniqueWithoutProductInput | Prisma.TransactionProductUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.TransactionProductUpdateManyWithWhereWithoutProductInput | Prisma.TransactionProductUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.TransactionProductScalarWhereInput | Prisma.TransactionProductScalarWhereInput[]
}

export type TransactionProductUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionProductCreateWithoutProductInput, Prisma.TransactionProductUncheckedCreateWithoutProductInput> | Prisma.TransactionProductCreateWithoutProductInput[] | Prisma.TransactionProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.TransactionProductCreateOrConnectWithoutProductInput | Prisma.TransactionProductCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.TransactionProductUpsertWithWhereUniqueWithoutProductInput | Prisma.TransactionProductUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.TransactionProductCreateManyProductInputEnvelope
  set?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  disconnect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  delete?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  connect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  update?: Prisma.TransactionProductUpdateWithWhereUniqueWithoutProductInput | Prisma.TransactionProductUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.TransactionProductUpdateManyWithWhereWithoutProductInput | Prisma.TransactionProductUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.TransactionProductScalarWhereInput | Prisma.TransactionProductScalarWhereInput[]
}

export type TransactionProductCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.TransactionProductCreateWithoutTransactionInput, Prisma.TransactionProductUncheckedCreateWithoutTransactionInput> | Prisma.TransactionProductCreateWithoutTransactionInput[] | Prisma.TransactionProductUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransactionProductCreateOrConnectWithoutTransactionInput | Prisma.TransactionProductCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.TransactionProductCreateManyTransactionInputEnvelope
  connect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
}

export type TransactionProductUncheckedCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.TransactionProductCreateWithoutTransactionInput, Prisma.TransactionProductUncheckedCreateWithoutTransactionInput> | Prisma.TransactionProductCreateWithoutTransactionInput[] | Prisma.TransactionProductUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransactionProductCreateOrConnectWithoutTransactionInput | Prisma.TransactionProductCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.TransactionProductCreateManyTransactionInputEnvelope
  connect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
}

export type TransactionProductUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionProductCreateWithoutTransactionInput, Prisma.TransactionProductUncheckedCreateWithoutTransactionInput> | Prisma.TransactionProductCreateWithoutTransactionInput[] | Prisma.TransactionProductUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransactionProductCreateOrConnectWithoutTransactionInput | Prisma.TransactionProductCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.TransactionProductUpsertWithWhereUniqueWithoutTransactionInput | Prisma.TransactionProductUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.TransactionProductCreateManyTransactionInputEnvelope
  set?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  disconnect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  delete?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  connect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  update?: Prisma.TransactionProductUpdateWithWhereUniqueWithoutTransactionInput | Prisma.TransactionProductUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.TransactionProductUpdateManyWithWhereWithoutTransactionInput | Prisma.TransactionProductUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.TransactionProductScalarWhereInput | Prisma.TransactionProductScalarWhereInput[]
}

export type TransactionProductUncheckedUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionProductCreateWithoutTransactionInput, Prisma.TransactionProductUncheckedCreateWithoutTransactionInput> | Prisma.TransactionProductCreateWithoutTransactionInput[] | Prisma.TransactionProductUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransactionProductCreateOrConnectWithoutTransactionInput | Prisma.TransactionProductCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.TransactionProductUpsertWithWhereUniqueWithoutTransactionInput | Prisma.TransactionProductUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.TransactionProductCreateManyTransactionInputEnvelope
  set?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  disconnect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  delete?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  connect?: Prisma.TransactionProductWhereUniqueInput | Prisma.TransactionProductWhereUniqueInput[]
  update?: Prisma.TransactionProductUpdateWithWhereUniqueWithoutTransactionInput | Prisma.TransactionProductUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.TransactionProductUpdateManyWithWhereWithoutTransactionInput | Prisma.TransactionProductUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.TransactionProductScalarWhereInput | Prisma.TransactionProductScalarWhereInput[]
}

export type TransactionProductCreateWithoutProductInput = {
  id?: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  transaction: Prisma.TransactionCreateNestedOneWithoutProductsInput
}

export type TransactionProductUncheckedCreateWithoutProductInput = {
  id?: string
  transactionId: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionProductCreateOrConnectWithoutProductInput = {
  where: Prisma.TransactionProductWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionProductCreateWithoutProductInput, Prisma.TransactionProductUncheckedCreateWithoutProductInput>
}

export type TransactionProductCreateManyProductInputEnvelope = {
  data: Prisma.TransactionProductCreateManyProductInput | Prisma.TransactionProductCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type TransactionProductUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.TransactionProductWhereUniqueInput
  update: Prisma.XOR<Prisma.TransactionProductUpdateWithoutProductInput, Prisma.TransactionProductUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.TransactionProductCreateWithoutProductInput, Prisma.TransactionProductUncheckedCreateWithoutProductInput>
}

export type TransactionProductUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.TransactionProductWhereUniqueInput
  data: Prisma.XOR<Prisma.TransactionProductUpdateWithoutProductInput, Prisma.TransactionProductUncheckedUpdateWithoutProductInput>
}

export type TransactionProductUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.TransactionProductScalarWhereInput
  data: Prisma.XOR<Prisma.TransactionProductUpdateManyMutationInput, Prisma.TransactionProductUncheckedUpdateManyWithoutProductInput>
}

export type TransactionProductScalarWhereInput = {
  AND?: Prisma.TransactionProductScalarWhereInput | Prisma.TransactionProductScalarWhereInput[]
  OR?: Prisma.TransactionProductScalarWhereInput[]
  NOT?: Prisma.TransactionProductScalarWhereInput | Prisma.TransactionProductScalarWhereInput[]
  id?: Prisma.StringFilter<"TransactionProduct"> | string
  productId?: Prisma.StringFilter<"TransactionProduct"> | string
  transactionId?: Prisma.StringFilter<"TransactionProduct"> | string
  quantity?: Prisma.IntFilter<"TransactionProduct"> | number
  unitPrice?: Prisma.IntFilter<"TransactionProduct"> | number
  totalAmount?: Prisma.IntFilter<"TransactionProduct"> | number
  createdAt?: Prisma.DateTimeFilter<"TransactionProduct"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TransactionProduct"> | Date | string
}

export type TransactionProductCreateWithoutTransactionInput = {
  id?: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutTransactionProductInput
}

export type TransactionProductUncheckedCreateWithoutTransactionInput = {
  id?: string
  productId: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionProductCreateOrConnectWithoutTransactionInput = {
  where: Prisma.TransactionProductWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionProductCreateWithoutTransactionInput, Prisma.TransactionProductUncheckedCreateWithoutTransactionInput>
}

export type TransactionProductCreateManyTransactionInputEnvelope = {
  data: Prisma.TransactionProductCreateManyTransactionInput | Prisma.TransactionProductCreateManyTransactionInput[]
  skipDuplicates?: boolean
}

export type TransactionProductUpsertWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.TransactionProductWhereUniqueInput
  update: Prisma.XOR<Prisma.TransactionProductUpdateWithoutTransactionInput, Prisma.TransactionProductUncheckedUpdateWithoutTransactionInput>
  create: Prisma.XOR<Prisma.TransactionProductCreateWithoutTransactionInput, Prisma.TransactionProductUncheckedCreateWithoutTransactionInput>
}

export type TransactionProductUpdateWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.TransactionProductWhereUniqueInput
  data: Prisma.XOR<Prisma.TransactionProductUpdateWithoutTransactionInput, Prisma.TransactionProductUncheckedUpdateWithoutTransactionInput>
}

export type TransactionProductUpdateManyWithWhereWithoutTransactionInput = {
  where: Prisma.TransactionProductScalarWhereInput
  data: Prisma.XOR<Prisma.TransactionProductUpdateManyMutationInput, Prisma.TransactionProductUncheckedUpdateManyWithoutTransactionInput>
}

export type TransactionProductCreateManyProductInput = {
  id?: string
  transactionId: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionProductUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transaction?: Prisma.TransactionUpdateOneRequiredWithoutProductsNestedInput
}

export type TransactionProductUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionProductUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionProductCreateManyTransactionInput = {
  id?: string
  productId: string
  quantity: number
  unitPrice: number
  totalAmount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionProductUpdateWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutTransactionProductNestedInput
}

export type TransactionProductUncheckedUpdateWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionProductUncheckedUpdateManyWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TransactionProductSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  transactionId?: boolean
  quantity?: boolean
  unitPrice?: boolean
  totalAmount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionProduct"]>

export type TransactionProductSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  transactionId?: boolean
  quantity?: boolean
  unitPrice?: boolean
  totalAmount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionProduct"]>

export type TransactionProductSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  transactionId?: boolean
  quantity?: boolean
  unitPrice?: boolean
  totalAmount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionProduct"]>

export type TransactionProductSelectScalar = {
  id?: boolean
  productId?: boolean
  transactionId?: boolean
  quantity?: boolean
  unitPrice?: boolean
  totalAmount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TransactionProductOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "transactionId" | "quantity" | "unitPrice" | "totalAmount" | "createdAt" | "updatedAt", ExtArgs["result"]["transactionProduct"]>
export type TransactionProductInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}
export type TransactionProductIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}
export type TransactionProductIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}

export type $TransactionProductPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TransactionProduct"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
    transaction: Prisma.$TransactionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    transactionId: string
    quantity: number
    unitPrice: number
    totalAmount: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["transactionProduct"]>
  composites: {}
}

export type TransactionProductGetPayload<S extends boolean | null | undefined | TransactionProductDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload, S>

export type TransactionProductCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TransactionProductFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TransactionProductCountAggregateInputType | true
  }

export interface TransactionProductDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TransactionProduct'], meta: { name: 'TransactionProduct' } }
  /**
   * Find zero or one TransactionProduct that matches the filter.
   * @param {TransactionProductFindUniqueArgs} args - Arguments to find a TransactionProduct
   * @example
   * // Get one TransactionProduct
   * const transactionProduct = await prisma.transactionProduct.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TransactionProductFindUniqueArgs>(args: Prisma.SelectSubset<T, TransactionProductFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TransactionProductClient<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TransactionProduct that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TransactionProductFindUniqueOrThrowArgs} args - Arguments to find a TransactionProduct
   * @example
   * // Get one TransactionProduct
   * const transactionProduct = await prisma.transactionProduct.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TransactionProductFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TransactionProductFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransactionProductClient<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TransactionProduct that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionProductFindFirstArgs} args - Arguments to find a TransactionProduct
   * @example
   * // Get one TransactionProduct
   * const transactionProduct = await prisma.transactionProduct.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TransactionProductFindFirstArgs>(args?: Prisma.SelectSubset<T, TransactionProductFindFirstArgs<ExtArgs>>): Prisma.Prisma__TransactionProductClient<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TransactionProduct that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionProductFindFirstOrThrowArgs} args - Arguments to find a TransactionProduct
   * @example
   * // Get one TransactionProduct
   * const transactionProduct = await prisma.transactionProduct.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TransactionProductFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TransactionProductFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransactionProductClient<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TransactionProducts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionProductFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TransactionProducts
   * const transactionProducts = await prisma.transactionProduct.findMany()
   * 
   * // Get first 10 TransactionProducts
   * const transactionProducts = await prisma.transactionProduct.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const transactionProductWithIdOnly = await prisma.transactionProduct.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TransactionProductFindManyArgs>(args?: Prisma.SelectSubset<T, TransactionProductFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TransactionProduct.
   * @param {TransactionProductCreateArgs} args - Arguments to create a TransactionProduct.
   * @example
   * // Create one TransactionProduct
   * const TransactionProduct = await prisma.transactionProduct.create({
   *   data: {
   *     // ... data to create a TransactionProduct
   *   }
   * })
   * 
   */
  create<T extends TransactionProductCreateArgs>(args: Prisma.SelectSubset<T, TransactionProductCreateArgs<ExtArgs>>): Prisma.Prisma__TransactionProductClient<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TransactionProducts.
   * @param {TransactionProductCreateManyArgs} args - Arguments to create many TransactionProducts.
   * @example
   * // Create many TransactionProducts
   * const transactionProduct = await prisma.transactionProduct.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TransactionProductCreateManyArgs>(args?: Prisma.SelectSubset<T, TransactionProductCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TransactionProducts and returns the data saved in the database.
   * @param {TransactionProductCreateManyAndReturnArgs} args - Arguments to create many TransactionProducts.
   * @example
   * // Create many TransactionProducts
   * const transactionProduct = await prisma.transactionProduct.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TransactionProducts and only return the `id`
   * const transactionProductWithIdOnly = await prisma.transactionProduct.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TransactionProductCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TransactionProductCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TransactionProduct.
   * @param {TransactionProductDeleteArgs} args - Arguments to delete one TransactionProduct.
   * @example
   * // Delete one TransactionProduct
   * const TransactionProduct = await prisma.transactionProduct.delete({
   *   where: {
   *     // ... filter to delete one TransactionProduct
   *   }
   * })
   * 
   */
  delete<T extends TransactionProductDeleteArgs>(args: Prisma.SelectSubset<T, TransactionProductDeleteArgs<ExtArgs>>): Prisma.Prisma__TransactionProductClient<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TransactionProduct.
   * @param {TransactionProductUpdateArgs} args - Arguments to update one TransactionProduct.
   * @example
   * // Update one TransactionProduct
   * const transactionProduct = await prisma.transactionProduct.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TransactionProductUpdateArgs>(args: Prisma.SelectSubset<T, TransactionProductUpdateArgs<ExtArgs>>): Prisma.Prisma__TransactionProductClient<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TransactionProducts.
   * @param {TransactionProductDeleteManyArgs} args - Arguments to filter TransactionProducts to delete.
   * @example
   * // Delete a few TransactionProducts
   * const { count } = await prisma.transactionProduct.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TransactionProductDeleteManyArgs>(args?: Prisma.SelectSubset<T, TransactionProductDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TransactionProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionProductUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TransactionProducts
   * const transactionProduct = await prisma.transactionProduct.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TransactionProductUpdateManyArgs>(args: Prisma.SelectSubset<T, TransactionProductUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TransactionProducts and returns the data updated in the database.
   * @param {TransactionProductUpdateManyAndReturnArgs} args - Arguments to update many TransactionProducts.
   * @example
   * // Update many TransactionProducts
   * const transactionProduct = await prisma.transactionProduct.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TransactionProducts and only return the `id`
   * const transactionProductWithIdOnly = await prisma.transactionProduct.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TransactionProductUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TransactionProductUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TransactionProduct.
   * @param {TransactionProductUpsertArgs} args - Arguments to update or create a TransactionProduct.
   * @example
   * // Update or create a TransactionProduct
   * const transactionProduct = await prisma.transactionProduct.upsert({
   *   create: {
   *     // ... data to create a TransactionProduct
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TransactionProduct we want to update
   *   }
   * })
   */
  upsert<T extends TransactionProductUpsertArgs>(args: Prisma.SelectSubset<T, TransactionProductUpsertArgs<ExtArgs>>): Prisma.Prisma__TransactionProductClient<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TransactionProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionProductCountArgs} args - Arguments to filter TransactionProducts to count.
   * @example
   * // Count the number of TransactionProducts
   * const count = await prisma.transactionProduct.count({
   *   where: {
   *     // ... the filter for the TransactionProducts we want to count
   *   }
   * })
  **/
  count<T extends TransactionProductCountArgs>(
    args?: Prisma.Subset<T, TransactionProductCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TransactionProductCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TransactionProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionProductAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TransactionProductAggregateArgs>(args: Prisma.Subset<T, TransactionProductAggregateArgs>): Prisma.PrismaPromise<GetTransactionProductAggregateType<T>>

  /**
   * Group by TransactionProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionProductGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TransactionProductGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TransactionProductGroupByArgs['orderBy'] }
      : { orderBy?: TransactionProductGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TransactionProductGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTransactionProductGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TransactionProduct model
 */
readonly fields: TransactionProductFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TransactionProduct.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TransactionProductClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  transaction<T extends Prisma.TransactionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TransactionDefaultArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TransactionProduct model
 */
export interface TransactionProductFieldRefs {
  readonly id: Prisma.FieldRef<"TransactionProduct", 'String'>
  readonly productId: Prisma.FieldRef<"TransactionProduct", 'String'>
  readonly transactionId: Prisma.FieldRef<"TransactionProduct", 'String'>
  readonly quantity: Prisma.FieldRef<"TransactionProduct", 'Int'>
  readonly unitPrice: Prisma.FieldRef<"TransactionProduct", 'Int'>
  readonly totalAmount: Prisma.FieldRef<"TransactionProduct", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TransactionProduct", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TransactionProduct", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TransactionProduct findUnique
 */
export type TransactionProductFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * Filter, which TransactionProduct to fetch.
   */
  where: Prisma.TransactionProductWhereUniqueInput
}

/**
 * TransactionProduct findUniqueOrThrow
 */
export type TransactionProductFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * Filter, which TransactionProduct to fetch.
   */
  where: Prisma.TransactionProductWhereUniqueInput
}

/**
 * TransactionProduct findFirst
 */
export type TransactionProductFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * Filter, which TransactionProduct to fetch.
   */
  where?: Prisma.TransactionProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionProducts to fetch.
   */
  orderBy?: Prisma.TransactionProductOrderByWithRelationInput | Prisma.TransactionProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TransactionProducts.
   */
  cursor?: Prisma.TransactionProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransactionProducts.
   */
  distinct?: Prisma.TransactionProductScalarFieldEnum | Prisma.TransactionProductScalarFieldEnum[]
}

/**
 * TransactionProduct findFirstOrThrow
 */
export type TransactionProductFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * Filter, which TransactionProduct to fetch.
   */
  where?: Prisma.TransactionProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionProducts to fetch.
   */
  orderBy?: Prisma.TransactionProductOrderByWithRelationInput | Prisma.TransactionProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TransactionProducts.
   */
  cursor?: Prisma.TransactionProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransactionProducts.
   */
  distinct?: Prisma.TransactionProductScalarFieldEnum | Prisma.TransactionProductScalarFieldEnum[]
}

/**
 * TransactionProduct findMany
 */
export type TransactionProductFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * Filter, which TransactionProducts to fetch.
   */
  where?: Prisma.TransactionProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionProducts to fetch.
   */
  orderBy?: Prisma.TransactionProductOrderByWithRelationInput | Prisma.TransactionProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TransactionProducts.
   */
  cursor?: Prisma.TransactionProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionProducts.
   */
  skip?: number
  distinct?: Prisma.TransactionProductScalarFieldEnum | Prisma.TransactionProductScalarFieldEnum[]
}

/**
 * TransactionProduct create
 */
export type TransactionProductCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * The data needed to create a TransactionProduct.
   */
  data: Prisma.XOR<Prisma.TransactionProductCreateInput, Prisma.TransactionProductUncheckedCreateInput>
}

/**
 * TransactionProduct createMany
 */
export type TransactionProductCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TransactionProducts.
   */
  data: Prisma.TransactionProductCreateManyInput | Prisma.TransactionProductCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TransactionProduct createManyAndReturn
 */
export type TransactionProductCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * The data used to create many TransactionProducts.
   */
  data: Prisma.TransactionProductCreateManyInput | Prisma.TransactionProductCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TransactionProduct update
 */
export type TransactionProductUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * The data needed to update a TransactionProduct.
   */
  data: Prisma.XOR<Prisma.TransactionProductUpdateInput, Prisma.TransactionProductUncheckedUpdateInput>
  /**
   * Choose, which TransactionProduct to update.
   */
  where: Prisma.TransactionProductWhereUniqueInput
}

/**
 * TransactionProduct updateMany
 */
export type TransactionProductUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TransactionProducts.
   */
  data: Prisma.XOR<Prisma.TransactionProductUpdateManyMutationInput, Prisma.TransactionProductUncheckedUpdateManyInput>
  /**
   * Filter which TransactionProducts to update
   */
  where?: Prisma.TransactionProductWhereInput
  /**
   * Limit how many TransactionProducts to update.
   */
  limit?: number
}

/**
 * TransactionProduct updateManyAndReturn
 */
export type TransactionProductUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * The data used to update TransactionProducts.
   */
  data: Prisma.XOR<Prisma.TransactionProductUpdateManyMutationInput, Prisma.TransactionProductUncheckedUpdateManyInput>
  /**
   * Filter which TransactionProducts to update
   */
  where?: Prisma.TransactionProductWhereInput
  /**
   * Limit how many TransactionProducts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TransactionProduct upsert
 */
export type TransactionProductUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * The filter to search for the TransactionProduct to update in case it exists.
   */
  where: Prisma.TransactionProductWhereUniqueInput
  /**
   * In case the TransactionProduct found by the `where` argument doesn't exist, create a new TransactionProduct with this data.
   */
  create: Prisma.XOR<Prisma.TransactionProductCreateInput, Prisma.TransactionProductUncheckedCreateInput>
  /**
   * In case the TransactionProduct was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TransactionProductUpdateInput, Prisma.TransactionProductUncheckedUpdateInput>
}

/**
 * TransactionProduct delete
 */
export type TransactionProductDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  /**
   * Filter which TransactionProduct to delete.
   */
  where: Prisma.TransactionProductWhereUniqueInput
}

/**
 * TransactionProduct deleteMany
 */
export type TransactionProductDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TransactionProducts to delete
   */
  where?: Prisma.TransactionProductWhereInput
  /**
   * Limit how many TransactionProducts to delete.
   */
  limit?: number
}

/**
 * TransactionProduct without action
 */
export type TransactionProductDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
}
