
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Transaction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Transaction
 * 
 */
export type TransactionModel = runtime.Types.Result.DefaultSelection<Prisma.$TransactionPayload>

export type AggregateTransaction = {
  _count: TransactionCountAggregateOutputType | null
  _avg: TransactionAvgAggregateOutputType | null
  _sum: TransactionSumAggregateOutputType | null
  _min: TransactionMinAggregateOutputType | null
  _max: TransactionMaxAggregateOutputType | null
}

export type TransactionAvgAggregateOutputType = {
  subtotal: number | null
  baseFee: number | null
  deliveryFee: number | null
  totalAmount: number | null
}

export type TransactionSumAggregateOutputType = {
  subtotal: number | null
  baseFee: number | null
  deliveryFee: number | null
  totalAmount: number | null
}

export type TransactionMinAggregateOutputType = {
  id: string | null
  status: $Enums.TransactionStatus | null
  subtotal: number | null
  baseFee: number | null
  deliveryFee: number | null
  totalAmount: number | null
  currency: $Enums.Currency | null
  customerId: string | null
  deliveryId: string | null
  externalTransactionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TransactionMaxAggregateOutputType = {
  id: string | null
  status: $Enums.TransactionStatus | null
  subtotal: number | null
  baseFee: number | null
  deliveryFee: number | null
  totalAmount: number | null
  currency: $Enums.Currency | null
  customerId: string | null
  deliveryId: string | null
  externalTransactionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TransactionCountAggregateOutputType = {
  id: number
  status: number
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency: number
  customerId: number
  deliveryId: number
  externalTransactionId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TransactionAvgAggregateInputType = {
  subtotal?: true
  baseFee?: true
  deliveryFee?: true
  totalAmount?: true
}

export type TransactionSumAggregateInputType = {
  subtotal?: true
  baseFee?: true
  deliveryFee?: true
  totalAmount?: true
}

export type TransactionMinAggregateInputType = {
  id?: true
  status?: true
  subtotal?: true
  baseFee?: true
  deliveryFee?: true
  totalAmount?: true
  currency?: true
  customerId?: true
  deliveryId?: true
  externalTransactionId?: true
  createdAt?: true
  updatedAt?: true
}

export type TransactionMaxAggregateInputType = {
  id?: true
  status?: true
  subtotal?: true
  baseFee?: true
  deliveryFee?: true
  totalAmount?: true
  currency?: true
  customerId?: true
  deliveryId?: true
  externalTransactionId?: true
  createdAt?: true
  updatedAt?: true
}

export type TransactionCountAggregateInputType = {
  id?: true
  status?: true
  subtotal?: true
  baseFee?: true
  deliveryFee?: true
  totalAmount?: true
  currency?: true
  customerId?: true
  deliveryId?: true
  externalTransactionId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TransactionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Transaction to aggregate.
   */
  where?: Prisma.TransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transactions to fetch.
   */
  orderBy?: Prisma.TransactionOrderByWithRelationInput | Prisma.TransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Transactions
  **/
  _count?: true | TransactionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TransactionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TransactionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TransactionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TransactionMaxAggregateInputType
}

export type GetTransactionAggregateType<T extends TransactionAggregateArgs> = {
      [P in keyof T & keyof AggregateTransaction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTransaction[P]>
    : Prisma.GetScalarType<T[P], AggregateTransaction[P]>
}




export type TransactionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransactionWhereInput
  orderBy?: Prisma.TransactionOrderByWithAggregationInput | Prisma.TransactionOrderByWithAggregationInput[]
  by: Prisma.TransactionScalarFieldEnum[] | Prisma.TransactionScalarFieldEnum
  having?: Prisma.TransactionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TransactionCountAggregateInputType | true
  _avg?: TransactionAvgAggregateInputType
  _sum?: TransactionSumAggregateInputType
  _min?: TransactionMinAggregateInputType
  _max?: TransactionMaxAggregateInputType
}

export type TransactionGroupByOutputType = {
  id: string
  status: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency: $Enums.Currency
  customerId: string
  deliveryId: string | null
  externalTransactionId: string
  createdAt: Date
  updatedAt: Date
  _count: TransactionCountAggregateOutputType | null
  _avg: TransactionAvgAggregateOutputType | null
  _sum: TransactionSumAggregateOutputType | null
  _min: TransactionMinAggregateOutputType | null
  _max: TransactionMaxAggregateOutputType | null
}

type GetTransactionGroupByPayload<T extends TransactionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TransactionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TransactionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TransactionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TransactionGroupByOutputType[P]>
      }
    >
  >



export type TransactionWhereInput = {
  AND?: Prisma.TransactionWhereInput | Prisma.TransactionWhereInput[]
  OR?: Prisma.TransactionWhereInput[]
  NOT?: Prisma.TransactionWhereInput | Prisma.TransactionWhereInput[]
  id?: Prisma.StringFilter<"Transaction"> | string
  status?: Prisma.EnumTransactionStatusFilter<"Transaction"> | $Enums.TransactionStatus
  subtotal?: Prisma.IntFilter<"Transaction"> | number
  baseFee?: Prisma.IntFilter<"Transaction"> | number
  deliveryFee?: Prisma.IntFilter<"Transaction"> | number
  totalAmount?: Prisma.IntFilter<"Transaction"> | number
  currency?: Prisma.EnumCurrencyFilter<"Transaction"> | $Enums.Currency
  customerId?: Prisma.StringFilter<"Transaction"> | string
  deliveryId?: Prisma.StringNullableFilter<"Transaction"> | string | null
  externalTransactionId?: Prisma.StringFilter<"Transaction"> | string
  createdAt?: Prisma.DateTimeFilter<"Transaction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Transaction"> | Date | string
  customer?: Prisma.XOR<Prisma.CustomerScalarRelationFilter, Prisma.CustomerWhereInput>
  delivery?: Prisma.XOR<Prisma.DeliveryNullableScalarRelationFilter, Prisma.DeliveryWhereInput> | null
  products?: Prisma.TransactionProductListRelationFilter
}

export type TransactionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  baseFee?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  deliveryId?: Prisma.SortOrderInput | Prisma.SortOrder
  externalTransactionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  customer?: Prisma.CustomerOrderByWithRelationInput
  delivery?: Prisma.DeliveryOrderByWithRelationInput
  products?: Prisma.TransactionProductOrderByRelationAggregateInput
}

export type TransactionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TransactionWhereInput | Prisma.TransactionWhereInput[]
  OR?: Prisma.TransactionWhereInput[]
  NOT?: Prisma.TransactionWhereInput | Prisma.TransactionWhereInput[]
  status?: Prisma.EnumTransactionStatusFilter<"Transaction"> | $Enums.TransactionStatus
  subtotal?: Prisma.IntFilter<"Transaction"> | number
  baseFee?: Prisma.IntFilter<"Transaction"> | number
  deliveryFee?: Prisma.IntFilter<"Transaction"> | number
  totalAmount?: Prisma.IntFilter<"Transaction"> | number
  currency?: Prisma.EnumCurrencyFilter<"Transaction"> | $Enums.Currency
  customerId?: Prisma.StringFilter<"Transaction"> | string
  deliveryId?: Prisma.StringNullableFilter<"Transaction"> | string | null
  externalTransactionId?: Prisma.StringFilter<"Transaction"> | string
  createdAt?: Prisma.DateTimeFilter<"Transaction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Transaction"> | Date | string
  customer?: Prisma.XOR<Prisma.CustomerScalarRelationFilter, Prisma.CustomerWhereInput>
  delivery?: Prisma.XOR<Prisma.DeliveryNullableScalarRelationFilter, Prisma.DeliveryWhereInput> | null
  products?: Prisma.TransactionProductListRelationFilter
}, "id">

export type TransactionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  baseFee?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  deliveryId?: Prisma.SortOrderInput | Prisma.SortOrder
  externalTransactionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TransactionCountOrderByAggregateInput
  _avg?: Prisma.TransactionAvgOrderByAggregateInput
  _max?: Prisma.TransactionMaxOrderByAggregateInput
  _min?: Prisma.TransactionMinOrderByAggregateInput
  _sum?: Prisma.TransactionSumOrderByAggregateInput
}

export type TransactionScalarWhereWithAggregatesInput = {
  AND?: Prisma.TransactionScalarWhereWithAggregatesInput | Prisma.TransactionScalarWhereWithAggregatesInput[]
  OR?: Prisma.TransactionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TransactionScalarWhereWithAggregatesInput | Prisma.TransactionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Transaction"> | string
  status?: Prisma.EnumTransactionStatusWithAggregatesFilter<"Transaction"> | $Enums.TransactionStatus
  subtotal?: Prisma.IntWithAggregatesFilter<"Transaction"> | number
  baseFee?: Prisma.IntWithAggregatesFilter<"Transaction"> | number
  deliveryFee?: Prisma.IntWithAggregatesFilter<"Transaction"> | number
  totalAmount?: Prisma.IntWithAggregatesFilter<"Transaction"> | number
  currency?: Prisma.EnumCurrencyWithAggregatesFilter<"Transaction"> | $Enums.Currency
  customerId?: Prisma.StringWithAggregatesFilter<"Transaction"> | string
  deliveryId?: Prisma.StringNullableWithAggregatesFilter<"Transaction"> | string | null
  externalTransactionId?: Prisma.StringWithAggregatesFilter<"Transaction"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Transaction"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Transaction"> | Date | string
}

export type TransactionCreateInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.CustomerCreateNestedOneWithoutTransactionsInput
  delivery?: Prisma.DeliveryCreateNestedOneWithoutTransactionsInput
  products?: Prisma.TransactionProductCreateNestedManyWithoutTransactionInput
}

export type TransactionUncheckedCreateInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  customerId: string
  deliveryId?: string | null
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.TransactionProductUncheckedCreateNestedManyWithoutTransactionInput
}

export type TransactionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.CustomerUpdateOneRequiredWithoutTransactionsNestedInput
  delivery?: Prisma.DeliveryUpdateOneWithoutTransactionsNestedInput
  products?: Prisma.TransactionProductUpdateManyWithoutTransactionNestedInput
}

export type TransactionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  deliveryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.TransactionProductUncheckedUpdateManyWithoutTransactionNestedInput
}

export type TransactionCreateManyInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  customerId: string
  deliveryId?: string | null
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  deliveryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  baseFee?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  deliveryId?: Prisma.SortOrder
  externalTransactionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransactionAvgOrderByAggregateInput = {
  subtotal?: Prisma.SortOrder
  baseFee?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type TransactionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  baseFee?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  deliveryId?: Prisma.SortOrder
  externalTransactionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransactionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  baseFee?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  deliveryId?: Prisma.SortOrder
  externalTransactionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TransactionSumOrderByAggregateInput = {
  subtotal?: Prisma.SortOrder
  baseFee?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type TransactionScalarRelationFilter = {
  is?: Prisma.TransactionWhereInput
  isNot?: Prisma.TransactionWhereInput
}

export type TransactionListRelationFilter = {
  every?: Prisma.TransactionWhereInput
  some?: Prisma.TransactionWhereInput
  none?: Prisma.TransactionWhereInput
}

export type TransactionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EnumTransactionStatusFieldUpdateOperationsInput = {
  set?: $Enums.TransactionStatus
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type TransactionCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutProductsInput, Prisma.TransactionUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutProductsInput
  connect?: Prisma.TransactionWhereUniqueInput
}

export type TransactionUpdateOneRequiredWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutProductsInput, Prisma.TransactionUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutProductsInput
  upsert?: Prisma.TransactionUpsertWithoutProductsInput
  connect?: Prisma.TransactionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TransactionUpdateToOneWithWhereWithoutProductsInput, Prisma.TransactionUpdateWithoutProductsInput>, Prisma.TransactionUncheckedUpdateWithoutProductsInput>
}

export type TransactionCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutCustomerInput, Prisma.TransactionUncheckedCreateWithoutCustomerInput> | Prisma.TransactionCreateWithoutCustomerInput[] | Prisma.TransactionUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutCustomerInput | Prisma.TransactionCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.TransactionCreateManyCustomerInputEnvelope
  connect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
}

export type TransactionUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutCustomerInput, Prisma.TransactionUncheckedCreateWithoutCustomerInput> | Prisma.TransactionCreateWithoutCustomerInput[] | Prisma.TransactionUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutCustomerInput | Prisma.TransactionCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.TransactionCreateManyCustomerInputEnvelope
  connect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
}

export type TransactionUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutCustomerInput, Prisma.TransactionUncheckedCreateWithoutCustomerInput> | Prisma.TransactionCreateWithoutCustomerInput[] | Prisma.TransactionUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutCustomerInput | Prisma.TransactionCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.TransactionUpsertWithWhereUniqueWithoutCustomerInput | Prisma.TransactionUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.TransactionCreateManyCustomerInputEnvelope
  set?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  disconnect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  delete?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  connect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  update?: Prisma.TransactionUpdateWithWhereUniqueWithoutCustomerInput | Prisma.TransactionUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.TransactionUpdateManyWithWhereWithoutCustomerInput | Prisma.TransactionUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.TransactionScalarWhereInput | Prisma.TransactionScalarWhereInput[]
}

export type TransactionUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutCustomerInput, Prisma.TransactionUncheckedCreateWithoutCustomerInput> | Prisma.TransactionCreateWithoutCustomerInput[] | Prisma.TransactionUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutCustomerInput | Prisma.TransactionCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.TransactionUpsertWithWhereUniqueWithoutCustomerInput | Prisma.TransactionUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.TransactionCreateManyCustomerInputEnvelope
  set?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  disconnect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  delete?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  connect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  update?: Prisma.TransactionUpdateWithWhereUniqueWithoutCustomerInput | Prisma.TransactionUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.TransactionUpdateManyWithWhereWithoutCustomerInput | Prisma.TransactionUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.TransactionScalarWhereInput | Prisma.TransactionScalarWhereInput[]
}

export type TransactionCreateNestedManyWithoutDeliveryInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutDeliveryInput, Prisma.TransactionUncheckedCreateWithoutDeliveryInput> | Prisma.TransactionCreateWithoutDeliveryInput[] | Prisma.TransactionUncheckedCreateWithoutDeliveryInput[]
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutDeliveryInput | Prisma.TransactionCreateOrConnectWithoutDeliveryInput[]
  createMany?: Prisma.TransactionCreateManyDeliveryInputEnvelope
  connect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
}

export type TransactionUncheckedCreateNestedManyWithoutDeliveryInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutDeliveryInput, Prisma.TransactionUncheckedCreateWithoutDeliveryInput> | Prisma.TransactionCreateWithoutDeliveryInput[] | Prisma.TransactionUncheckedCreateWithoutDeliveryInput[]
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutDeliveryInput | Prisma.TransactionCreateOrConnectWithoutDeliveryInput[]
  createMany?: Prisma.TransactionCreateManyDeliveryInputEnvelope
  connect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
}

export type TransactionUpdateManyWithoutDeliveryNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutDeliveryInput, Prisma.TransactionUncheckedCreateWithoutDeliveryInput> | Prisma.TransactionCreateWithoutDeliveryInput[] | Prisma.TransactionUncheckedCreateWithoutDeliveryInput[]
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutDeliveryInput | Prisma.TransactionCreateOrConnectWithoutDeliveryInput[]
  upsert?: Prisma.TransactionUpsertWithWhereUniqueWithoutDeliveryInput | Prisma.TransactionUpsertWithWhereUniqueWithoutDeliveryInput[]
  createMany?: Prisma.TransactionCreateManyDeliveryInputEnvelope
  set?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  disconnect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  delete?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  connect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  update?: Prisma.TransactionUpdateWithWhereUniqueWithoutDeliveryInput | Prisma.TransactionUpdateWithWhereUniqueWithoutDeliveryInput[]
  updateMany?: Prisma.TransactionUpdateManyWithWhereWithoutDeliveryInput | Prisma.TransactionUpdateManyWithWhereWithoutDeliveryInput[]
  deleteMany?: Prisma.TransactionScalarWhereInput | Prisma.TransactionScalarWhereInput[]
}

export type TransactionUncheckedUpdateManyWithoutDeliveryNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionCreateWithoutDeliveryInput, Prisma.TransactionUncheckedCreateWithoutDeliveryInput> | Prisma.TransactionCreateWithoutDeliveryInput[] | Prisma.TransactionUncheckedCreateWithoutDeliveryInput[]
  connectOrCreate?: Prisma.TransactionCreateOrConnectWithoutDeliveryInput | Prisma.TransactionCreateOrConnectWithoutDeliveryInput[]
  upsert?: Prisma.TransactionUpsertWithWhereUniqueWithoutDeliveryInput | Prisma.TransactionUpsertWithWhereUniqueWithoutDeliveryInput[]
  createMany?: Prisma.TransactionCreateManyDeliveryInputEnvelope
  set?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  disconnect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  delete?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  connect?: Prisma.TransactionWhereUniqueInput | Prisma.TransactionWhereUniqueInput[]
  update?: Prisma.TransactionUpdateWithWhereUniqueWithoutDeliveryInput | Prisma.TransactionUpdateWithWhereUniqueWithoutDeliveryInput[]
  updateMany?: Prisma.TransactionUpdateManyWithWhereWithoutDeliveryInput | Prisma.TransactionUpdateManyWithWhereWithoutDeliveryInput[]
  deleteMany?: Prisma.TransactionScalarWhereInput | Prisma.TransactionScalarWhereInput[]
}

export type TransactionCreateWithoutProductsInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.CustomerCreateNestedOneWithoutTransactionsInput
  delivery?: Prisma.DeliveryCreateNestedOneWithoutTransactionsInput
}

export type TransactionUncheckedCreateWithoutProductsInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  customerId: string
  deliveryId?: string | null
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionCreateOrConnectWithoutProductsInput = {
  where: Prisma.TransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionCreateWithoutProductsInput, Prisma.TransactionUncheckedCreateWithoutProductsInput>
}

export type TransactionUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.TransactionUpdateWithoutProductsInput, Prisma.TransactionUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.TransactionCreateWithoutProductsInput, Prisma.TransactionUncheckedCreateWithoutProductsInput>
  where?: Prisma.TransactionWhereInput
}

export type TransactionUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.TransactionWhereInput
  data: Prisma.XOR<Prisma.TransactionUpdateWithoutProductsInput, Prisma.TransactionUncheckedUpdateWithoutProductsInput>
}

export type TransactionUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.CustomerUpdateOneRequiredWithoutTransactionsNestedInput
  delivery?: Prisma.DeliveryUpdateOneWithoutTransactionsNestedInput
}

export type TransactionUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  deliveryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionCreateWithoutCustomerInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  delivery?: Prisma.DeliveryCreateNestedOneWithoutTransactionsInput
  products?: Prisma.TransactionProductCreateNestedManyWithoutTransactionInput
}

export type TransactionUncheckedCreateWithoutCustomerInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  deliveryId?: string | null
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.TransactionProductUncheckedCreateNestedManyWithoutTransactionInput
}

export type TransactionCreateOrConnectWithoutCustomerInput = {
  where: Prisma.TransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionCreateWithoutCustomerInput, Prisma.TransactionUncheckedCreateWithoutCustomerInput>
}

export type TransactionCreateManyCustomerInputEnvelope = {
  data: Prisma.TransactionCreateManyCustomerInput | Prisma.TransactionCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type TransactionUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.TransactionWhereUniqueInput
  update: Prisma.XOR<Prisma.TransactionUpdateWithoutCustomerInput, Prisma.TransactionUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.TransactionCreateWithoutCustomerInput, Prisma.TransactionUncheckedCreateWithoutCustomerInput>
}

export type TransactionUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.TransactionWhereUniqueInput
  data: Prisma.XOR<Prisma.TransactionUpdateWithoutCustomerInput, Prisma.TransactionUncheckedUpdateWithoutCustomerInput>
}

export type TransactionUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.TransactionScalarWhereInput
  data: Prisma.XOR<Prisma.TransactionUpdateManyMutationInput, Prisma.TransactionUncheckedUpdateManyWithoutCustomerInput>
}

export type TransactionScalarWhereInput = {
  AND?: Prisma.TransactionScalarWhereInput | Prisma.TransactionScalarWhereInput[]
  OR?: Prisma.TransactionScalarWhereInput[]
  NOT?: Prisma.TransactionScalarWhereInput | Prisma.TransactionScalarWhereInput[]
  id?: Prisma.StringFilter<"Transaction"> | string
  status?: Prisma.EnumTransactionStatusFilter<"Transaction"> | $Enums.TransactionStatus
  subtotal?: Prisma.IntFilter<"Transaction"> | number
  baseFee?: Prisma.IntFilter<"Transaction"> | number
  deliveryFee?: Prisma.IntFilter<"Transaction"> | number
  totalAmount?: Prisma.IntFilter<"Transaction"> | number
  currency?: Prisma.EnumCurrencyFilter<"Transaction"> | $Enums.Currency
  customerId?: Prisma.StringFilter<"Transaction"> | string
  deliveryId?: Prisma.StringNullableFilter<"Transaction"> | string | null
  externalTransactionId?: Prisma.StringFilter<"Transaction"> | string
  createdAt?: Prisma.DateTimeFilter<"Transaction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Transaction"> | Date | string
}

export type TransactionCreateWithoutDeliveryInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.CustomerCreateNestedOneWithoutTransactionsInput
  products?: Prisma.TransactionProductCreateNestedManyWithoutTransactionInput
}

export type TransactionUncheckedCreateWithoutDeliveryInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  customerId: string
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.TransactionProductUncheckedCreateNestedManyWithoutTransactionInput
}

export type TransactionCreateOrConnectWithoutDeliveryInput = {
  where: Prisma.TransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionCreateWithoutDeliveryInput, Prisma.TransactionUncheckedCreateWithoutDeliveryInput>
}

export type TransactionCreateManyDeliveryInputEnvelope = {
  data: Prisma.TransactionCreateManyDeliveryInput | Prisma.TransactionCreateManyDeliveryInput[]
  skipDuplicates?: boolean
}

export type TransactionUpsertWithWhereUniqueWithoutDeliveryInput = {
  where: Prisma.TransactionWhereUniqueInput
  update: Prisma.XOR<Prisma.TransactionUpdateWithoutDeliveryInput, Prisma.TransactionUncheckedUpdateWithoutDeliveryInput>
  create: Prisma.XOR<Prisma.TransactionCreateWithoutDeliveryInput, Prisma.TransactionUncheckedCreateWithoutDeliveryInput>
}

export type TransactionUpdateWithWhereUniqueWithoutDeliveryInput = {
  where: Prisma.TransactionWhereUniqueInput
  data: Prisma.XOR<Prisma.TransactionUpdateWithoutDeliveryInput, Prisma.TransactionUncheckedUpdateWithoutDeliveryInput>
}

export type TransactionUpdateManyWithWhereWithoutDeliveryInput = {
  where: Prisma.TransactionScalarWhereInput
  data: Prisma.XOR<Prisma.TransactionUpdateManyMutationInput, Prisma.TransactionUncheckedUpdateManyWithoutDeliveryInput>
}

export type TransactionCreateManyCustomerInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  deliveryId?: string | null
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  delivery?: Prisma.DeliveryUpdateOneWithoutTransactionsNestedInput
  products?: Prisma.TransactionProductUpdateManyWithoutTransactionNestedInput
}

export type TransactionUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  deliveryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.TransactionProductUncheckedUpdateManyWithoutTransactionNestedInput
}

export type TransactionUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  deliveryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TransactionCreateManyDeliveryInput = {
  id?: string
  status?: $Enums.TransactionStatus
  subtotal: number
  baseFee: number
  deliveryFee: number
  totalAmount: number
  currency?: $Enums.Currency
  customerId: string
  externalTransactionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TransactionUpdateWithoutDeliveryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.CustomerUpdateOneRequiredWithoutTransactionsNestedInput
  products?: Prisma.TransactionProductUpdateManyWithoutTransactionNestedInput
}

export type TransactionUncheckedUpdateWithoutDeliveryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.TransactionProductUncheckedUpdateManyWithoutTransactionNestedInput
}

export type TransactionUncheckedUpdateManyWithoutDeliveryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  subtotal?: Prisma.IntFieldUpdateOperationsInput | number
  baseFee?: Prisma.IntFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.EnumCurrencyFieldUpdateOperationsInput | $Enums.Currency
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  externalTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TransactionCountOutputType
 */

export type TransactionCountOutputType = {
  products: number
}

export type TransactionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | TransactionCountOutputTypeCountProductsArgs
}

/**
 * TransactionCountOutputType without action
 */
export type TransactionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionCountOutputType
   */
  select?: Prisma.TransactionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TransactionCountOutputType without action
 */
export type TransactionCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransactionProductWhereInput
}


export type TransactionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  subtotal?: boolean
  baseFee?: boolean
  deliveryFee?: boolean
  totalAmount?: boolean
  currency?: boolean
  customerId?: boolean
  deliveryId?: boolean
  externalTransactionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  delivery?: boolean | Prisma.Transaction$deliveryArgs<ExtArgs>
  products?: boolean | Prisma.Transaction$productsArgs<ExtArgs>
  _count?: boolean | Prisma.TransactionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transaction"]>

export type TransactionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  subtotal?: boolean
  baseFee?: boolean
  deliveryFee?: boolean
  totalAmount?: boolean
  currency?: boolean
  customerId?: boolean
  deliveryId?: boolean
  externalTransactionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  delivery?: boolean | Prisma.Transaction$deliveryArgs<ExtArgs>
}, ExtArgs["result"]["transaction"]>

export type TransactionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  subtotal?: boolean
  baseFee?: boolean
  deliveryFee?: boolean
  totalAmount?: boolean
  currency?: boolean
  customerId?: boolean
  deliveryId?: boolean
  externalTransactionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  delivery?: boolean | Prisma.Transaction$deliveryArgs<ExtArgs>
}, ExtArgs["result"]["transaction"]>

export type TransactionSelectScalar = {
  id?: boolean
  status?: boolean
  subtotal?: boolean
  baseFee?: boolean
  deliveryFee?: boolean
  totalAmount?: boolean
  currency?: boolean
  customerId?: boolean
  deliveryId?: boolean
  externalTransactionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TransactionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "status" | "subtotal" | "baseFee" | "deliveryFee" | "totalAmount" | "currency" | "customerId" | "deliveryId" | "externalTransactionId" | "createdAt" | "updatedAt", ExtArgs["result"]["transaction"]>
export type TransactionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  delivery?: boolean | Prisma.Transaction$deliveryArgs<ExtArgs>
  products?: boolean | Prisma.Transaction$productsArgs<ExtArgs>
  _count?: boolean | Prisma.TransactionCountOutputTypeDefaultArgs<ExtArgs>
}
export type TransactionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  delivery?: boolean | Prisma.Transaction$deliveryArgs<ExtArgs>
}
export type TransactionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  delivery?: boolean | Prisma.Transaction$deliveryArgs<ExtArgs>
}

export type $TransactionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Transaction"
  objects: {
    customer: Prisma.$CustomerPayload<ExtArgs>
    delivery: Prisma.$DeliveryPayload<ExtArgs> | null
    products: Prisma.$TransactionProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    status: $Enums.TransactionStatus
    subtotal: number
    baseFee: number
    deliveryFee: number
    totalAmount: number
    currency: $Enums.Currency
    customerId: string
    deliveryId: string | null
    externalTransactionId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["transaction"]>
  composites: {}
}

export type TransactionGetPayload<S extends boolean | null | undefined | TransactionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TransactionPayload, S>

export type TransactionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TransactionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TransactionCountAggregateInputType | true
  }

export interface TransactionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Transaction'], meta: { name: 'Transaction' } }
  /**
   * Find zero or one Transaction that matches the filter.
   * @param {TransactionFindUniqueArgs} args - Arguments to find a Transaction
   * @example
   * // Get one Transaction
   * const transaction = await prisma.transaction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TransactionFindUniqueArgs>(args: Prisma.SelectSubset<T, TransactionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Transaction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TransactionFindUniqueOrThrowArgs} args - Arguments to find a Transaction
   * @example
   * // Get one Transaction
   * const transaction = await prisma.transaction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TransactionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TransactionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Transaction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionFindFirstArgs} args - Arguments to find a Transaction
   * @example
   * // Get one Transaction
   * const transaction = await prisma.transaction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TransactionFindFirstArgs>(args?: Prisma.SelectSubset<T, TransactionFindFirstArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Transaction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionFindFirstOrThrowArgs} args - Arguments to find a Transaction
   * @example
   * // Get one Transaction
   * const transaction = await prisma.transaction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TransactionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TransactionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Transactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Transactions
   * const transactions = await prisma.transaction.findMany()
   * 
   * // Get first 10 Transactions
   * const transactions = await prisma.transaction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const transactionWithIdOnly = await prisma.transaction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TransactionFindManyArgs>(args?: Prisma.SelectSubset<T, TransactionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Transaction.
   * @param {TransactionCreateArgs} args - Arguments to create a Transaction.
   * @example
   * // Create one Transaction
   * const Transaction = await prisma.transaction.create({
   *   data: {
   *     // ... data to create a Transaction
   *   }
   * })
   * 
   */
  create<T extends TransactionCreateArgs>(args: Prisma.SelectSubset<T, TransactionCreateArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Transactions.
   * @param {TransactionCreateManyArgs} args - Arguments to create many Transactions.
   * @example
   * // Create many Transactions
   * const transaction = await prisma.transaction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TransactionCreateManyArgs>(args?: Prisma.SelectSubset<T, TransactionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Transactions and returns the data saved in the database.
   * @param {TransactionCreateManyAndReturnArgs} args - Arguments to create many Transactions.
   * @example
   * // Create many Transactions
   * const transaction = await prisma.transaction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Transactions and only return the `id`
   * const transactionWithIdOnly = await prisma.transaction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TransactionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TransactionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Transaction.
   * @param {TransactionDeleteArgs} args - Arguments to delete one Transaction.
   * @example
   * // Delete one Transaction
   * const Transaction = await prisma.transaction.delete({
   *   where: {
   *     // ... filter to delete one Transaction
   *   }
   * })
   * 
   */
  delete<T extends TransactionDeleteArgs>(args: Prisma.SelectSubset<T, TransactionDeleteArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Transaction.
   * @param {TransactionUpdateArgs} args - Arguments to update one Transaction.
   * @example
   * // Update one Transaction
   * const transaction = await prisma.transaction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TransactionUpdateArgs>(args: Prisma.SelectSubset<T, TransactionUpdateArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Transactions.
   * @param {TransactionDeleteManyArgs} args - Arguments to filter Transactions to delete.
   * @example
   * // Delete a few Transactions
   * const { count } = await prisma.transaction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TransactionDeleteManyArgs>(args?: Prisma.SelectSubset<T, TransactionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Transactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Transactions
   * const transaction = await prisma.transaction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TransactionUpdateManyArgs>(args: Prisma.SelectSubset<T, TransactionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Transactions and returns the data updated in the database.
   * @param {TransactionUpdateManyAndReturnArgs} args - Arguments to update many Transactions.
   * @example
   * // Update many Transactions
   * const transaction = await prisma.transaction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Transactions and only return the `id`
   * const transactionWithIdOnly = await prisma.transaction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TransactionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TransactionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Transaction.
   * @param {TransactionUpsertArgs} args - Arguments to update or create a Transaction.
   * @example
   * // Update or create a Transaction
   * const transaction = await prisma.transaction.upsert({
   *   create: {
   *     // ... data to create a Transaction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Transaction we want to update
   *   }
   * })
   */
  upsert<T extends TransactionUpsertArgs>(args: Prisma.SelectSubset<T, TransactionUpsertArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Transactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionCountArgs} args - Arguments to filter Transactions to count.
   * @example
   * // Count the number of Transactions
   * const count = await prisma.transaction.count({
   *   where: {
   *     // ... the filter for the Transactions we want to count
   *   }
   * })
  **/
  count<T extends TransactionCountArgs>(
    args?: Prisma.Subset<T, TransactionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TransactionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Transaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TransactionAggregateArgs>(args: Prisma.Subset<T, TransactionAggregateArgs>): Prisma.PrismaPromise<GetTransactionAggregateType<T>>

  /**
   * Group by Transaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TransactionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TransactionGroupByArgs['orderBy'] }
      : { orderBy?: TransactionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TransactionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTransactionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Transaction model
 */
readonly fields: TransactionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Transaction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TransactionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  customer<T extends Prisma.CustomerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CustomerDefaultArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  delivery<T extends Prisma.Transaction$deliveryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Transaction$deliveryArgs<ExtArgs>>): Prisma.Prisma__DeliveryClient<runtime.Types.Result.GetResult<Prisma.$DeliveryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  products<T extends Prisma.Transaction$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Transaction$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Transaction model
 */
export interface TransactionFieldRefs {
  readonly id: Prisma.FieldRef<"Transaction", 'String'>
  readonly status: Prisma.FieldRef<"Transaction", 'TransactionStatus'>
  readonly subtotal: Prisma.FieldRef<"Transaction", 'Int'>
  readonly baseFee: Prisma.FieldRef<"Transaction", 'Int'>
  readonly deliveryFee: Prisma.FieldRef<"Transaction", 'Int'>
  readonly totalAmount: Prisma.FieldRef<"Transaction", 'Int'>
  readonly currency: Prisma.FieldRef<"Transaction", 'Currency'>
  readonly customerId: Prisma.FieldRef<"Transaction", 'String'>
  readonly deliveryId: Prisma.FieldRef<"Transaction", 'String'>
  readonly externalTransactionId: Prisma.FieldRef<"Transaction", 'String'>
  readonly createdAt: Prisma.FieldRef<"Transaction", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Transaction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Transaction findUnique
 */
export type TransactionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * Filter, which Transaction to fetch.
   */
  where: Prisma.TransactionWhereUniqueInput
}

/**
 * Transaction findUniqueOrThrow
 */
export type TransactionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * Filter, which Transaction to fetch.
   */
  where: Prisma.TransactionWhereUniqueInput
}

/**
 * Transaction findFirst
 */
export type TransactionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * Filter, which Transaction to fetch.
   */
  where?: Prisma.TransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transactions to fetch.
   */
  orderBy?: Prisma.TransactionOrderByWithRelationInput | Prisma.TransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Transactions.
   */
  cursor?: Prisma.TransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Transactions.
   */
  distinct?: Prisma.TransactionScalarFieldEnum | Prisma.TransactionScalarFieldEnum[]
}

/**
 * Transaction findFirstOrThrow
 */
export type TransactionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * Filter, which Transaction to fetch.
   */
  where?: Prisma.TransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transactions to fetch.
   */
  orderBy?: Prisma.TransactionOrderByWithRelationInput | Prisma.TransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Transactions.
   */
  cursor?: Prisma.TransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Transactions.
   */
  distinct?: Prisma.TransactionScalarFieldEnum | Prisma.TransactionScalarFieldEnum[]
}

/**
 * Transaction findMany
 */
export type TransactionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * Filter, which Transactions to fetch.
   */
  where?: Prisma.TransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transactions to fetch.
   */
  orderBy?: Prisma.TransactionOrderByWithRelationInput | Prisma.TransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Transactions.
   */
  cursor?: Prisma.TransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transactions.
   */
  skip?: number
  distinct?: Prisma.TransactionScalarFieldEnum | Prisma.TransactionScalarFieldEnum[]
}

/**
 * Transaction create
 */
export type TransactionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * The data needed to create a Transaction.
   */
  data: Prisma.XOR<Prisma.TransactionCreateInput, Prisma.TransactionUncheckedCreateInput>
}

/**
 * Transaction createMany
 */
export type TransactionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Transactions.
   */
  data: Prisma.TransactionCreateManyInput | Prisma.TransactionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Transaction createManyAndReturn
 */
export type TransactionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * The data used to create many Transactions.
   */
  data: Prisma.TransactionCreateManyInput | Prisma.TransactionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Transaction update
 */
export type TransactionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * The data needed to update a Transaction.
   */
  data: Prisma.XOR<Prisma.TransactionUpdateInput, Prisma.TransactionUncheckedUpdateInput>
  /**
   * Choose, which Transaction to update.
   */
  where: Prisma.TransactionWhereUniqueInput
}

/**
 * Transaction updateMany
 */
export type TransactionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Transactions.
   */
  data: Prisma.XOR<Prisma.TransactionUpdateManyMutationInput, Prisma.TransactionUncheckedUpdateManyInput>
  /**
   * Filter which Transactions to update
   */
  where?: Prisma.TransactionWhereInput
  /**
   * Limit how many Transactions to update.
   */
  limit?: number
}

/**
 * Transaction updateManyAndReturn
 */
export type TransactionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * The data used to update Transactions.
   */
  data: Prisma.XOR<Prisma.TransactionUpdateManyMutationInput, Prisma.TransactionUncheckedUpdateManyInput>
  /**
   * Filter which Transactions to update
   */
  where?: Prisma.TransactionWhereInput
  /**
   * Limit how many Transactions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Transaction upsert
 */
export type TransactionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * The filter to search for the Transaction to update in case it exists.
   */
  where: Prisma.TransactionWhereUniqueInput
  /**
   * In case the Transaction found by the `where` argument doesn't exist, create a new Transaction with this data.
   */
  create: Prisma.XOR<Prisma.TransactionCreateInput, Prisma.TransactionUncheckedCreateInput>
  /**
   * In case the Transaction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TransactionUpdateInput, Prisma.TransactionUncheckedUpdateInput>
}

/**
 * Transaction delete
 */
export type TransactionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  /**
   * Filter which Transaction to delete.
   */
  where: Prisma.TransactionWhereUniqueInput
}

/**
 * Transaction deleteMany
 */
export type TransactionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Transactions to delete
   */
  where?: Prisma.TransactionWhereInput
  /**
   * Limit how many Transactions to delete.
   */
  limit?: number
}

/**
 * Transaction.delivery
 */
export type Transaction$deliveryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Delivery
   */
  select?: Prisma.DeliverySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Delivery
   */
  omit?: Prisma.DeliveryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliveryInclude<ExtArgs> | null
  where?: Prisma.DeliveryWhereInput
}

/**
 * Transaction.products
 */
export type Transaction$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionProduct
   */
  select?: Prisma.TransactionProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionProduct
   */
  omit?: Prisma.TransactionProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionProductInclude<ExtArgs> | null
  where?: Prisma.TransactionProductWhereInput
  orderBy?: Prisma.TransactionProductOrderByWithRelationInput | Prisma.TransactionProductOrderByWithRelationInput[]
  cursor?: Prisma.TransactionProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransactionProductScalarFieldEnum | Prisma.TransactionProductScalarFieldEnum[]
}

/**
 * Transaction without action
 */
export type TransactionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
}
